Repository project-codeflare/codeflare-operator, pull requests merged in 2023-06, with the labels that each got.

#116 Use Kustomize to bundle MCAD CRDs
  Makefile
  config/crd/bases/mcad.ibm.com_appwrappers.yaml
  config/crd/bases/mcad.ibm.com_queuejobs.yaml
  config/crd/bases/mcad.ibm.com_schedulingspecs.yaml
  config/crd/kustomization.yaml
  config/crd/mcad/kustomization.yaml
Labels: lgtm, approved

#120 feat(api): Support custom InstaScale container image
  Makefile
  api/v1alpha1/instascale_types.go
  config/crd/bases/codeflare.codeflare.dev_instascales.yaml
  config/internal/instascale/deployment.yaml.tmpl
  controllers/defaults.go
  controllers/instascale_controller.go
  controllers/instascale_params.go
Labels: lgtm, approved

#125 Remove generated OLM bundle Dockerfile
  .gitignore
  Makefile
  bundle.Dockerfile
Labels: lgtm, approved

#124 Add test for custom InstaScale controller image support
  controllers/instascale_controller_test.go
  controllers/testdata/instascale_test_cases/case_3.yaml
  controllers/testdata/instascale_test_results/case_3/deployment.yaml
Labels: lgtm, approved

#123 Update GitHub actions to avoid using deprecated actions
  .github/workflows/precommit.yml
  .github/workflows/tag-and-build.yml
  .github/workflows/unit_tests.yml
Labels: lgtm, approved

#133 Generate CodeFlare API client
  Makefile
  api/codeflare/v1alpha1/doc.go
  api/codeflare/v1alpha1/instascale_types.go
  api/codeflare/v1alpha1/mcad_types.go
  api/codeflare/v1alpha1/register.go
  api/codeflare/v1alpha1/zz_generated.deepcopy.go
  client/applyconfiguration/codeflare/v1alpha1/instascale.go
  client/applyconfiguration/codeflare/v1alpha1/instascalespec.go
  client/applyconfiguration/codeflare/v1alpha1/instascalestatus.go
  client/applyconfiguration/codeflare/v1alpha1/mcad.go
  client/applyconfiguration/codeflare/v1alpha1/mcadspec.go
  client/applyconfiguration/codeflare/v1alpha1/mcadstatus.go
  client/applyconfiguration/internal/internal.go
  client/applyconfiguration/utils.go
  client/clientset/versioned/clientset.go
  client/clientset/versioned/fake/clientset_generated.go
  client/clientset/versioned/fake/doc.go
  client/clientset/versioned/fake/register.go
  client/clientset/versioned/scheme/doc.go
  client/clientset/versioned/scheme/register.go
  client/clientset/versioned/typed/codeflare/v1alpha1/codeflare_client.go
  client/clientset/versioned/typed/codeflare/v1alpha1/doc.go
  client/clientset/versioned/typed/codeflare/v1alpha1/fake/doc.go
  client/clientset/versioned/typed/codeflare/v1alpha1/fake/fake_codeflare_client.go
  client/clientset/versioned/typed/codeflare/v1alpha1/fake/fake_instascale.go
  client/clientset/versioned/typed/codeflare/v1alpha1/fake/fake_mcad.go
  client/clientset/versioned/typed/codeflare/v1alpha1/generated_expansion.go
  client/clientset/versioned/typed/codeflare/v1alpha1/instascale.go
  client/clientset/versioned/typed/codeflare/v1alpha1/mcad.go
  client/informer/externalversions/codeflare/interface.go
  client/informer/externalversions/codeflare/v1alpha1/instascale.go
  client/informer/externalversions/codeflare/v1alpha1/interface.go
  client/informer/externalversions/codeflare/v1alpha1/mcad.go
  client/informer/externalversions/factory.go
  client/informer/externalversions/generic.go
  client/informer/externalversions/internalinterfaces/factory_interfaces.go
  client/listers/codeflare/v1alpha1/expansion_generated.go
  client/listers/codeflare/v1alpha1/instascale.go
  client/listers/codeflare/v1alpha1/mcad.go
  controllers/instascale.go
  controllers/instascale_controller.go
  controllers/instascale_controller_test.go
  controllers/instascale_params.go
  controllers/mcad_controller.go
  controllers/mcad_controller_test.go
  controllers/mcad_params.go
  controllers/multi_cluster_app_dispatcher.go
  controllers/suite_test.go
  go.mod
  main.go
Labels: lgtm, approved

#139 Add MCAD version variable
  Makefile
  config/crd/mcad/kustomization.yaml
Labels: lgtm, approved

#141 Extended support for referencing MCAD CRD resources
  Makefile
  config/crd/mcad/kustomization.yaml
Labels: lgtm, approved

#150 refactor: add liveness and readyness probes to instascale deployment
  config/internal/instascale/deployment.yaml.tmpl
Labels: lgtm

#144 perf: addition of liveness and readiness probes to mcad deployment
  config/internal/mcad/deployment.yaml.tmpl
Labels: do-not-merge/hold
