Repository project-codeflare/codeflare-operator, pull requests merged in 2023-07, with the labels that each got.

#163 doc: The operator should be started before setting up e2e tests
  README.md
Labels: lgtm, approved

#152 fix: Update MCAD version when installing CRDs
  Makefile
Labels: lgtm, approved

#174 Fix mcad tag reference for CRDs
  Makefile
Labels: lgtm

#177 Adjust Makefile versions before building operator image
  .github/workflows/tag-and-build.yml
Labels: lgtm, approved

#178 Update rbacs
  config/rbac/role.yaml
  controllers/instascale_controller.go
Labels: lgtm, approved

#180 Run go mod tidy before comitting files in release workflow
  .github/workflows/tag-and-build.yml
  go.sum
Labels: lgtm

#162 OLM install and upgrade PR check for CodeFlare stack
  .github/actions/kind/action.yml
  .github/resources-kind/kind.yaml
  .github/resources-olm-upgrade/catalogsource.yaml
  .github/resources-olm-upgrade/operatorgroup.yaml
  .github/resources-olm-upgrade/subscription.yaml
  .github/workflows/e2e_tests.yaml
  .github/workflows/olm_tests.yaml
  Makefile
Labels: lgtm, approved

#185 Expose CodeFlare Operator metrics endpoint
  config/default/manager_auth_proxy_patch.yaml
  config/rbac/auth_proxy_service.yaml
Labels: lgtm, approved

#194 Add Ray cluster support in test support package
  test/support/conditions.go
  test/support/ray.go
Labels: lgtm, approved

#192 Update: remove duplicated resource and should have lower in order
  controllers/mcad_controller.go
Labels: lgtm, approved, ok-to-test

#189 Remove waiting loops for kubernetes resources from Makefile
  .github/actions/kind/action.yml
  .github/workflows/olm_tests.yaml
  Makefile
Labels: lgtm, approved

#201 Release workflow - open a PR with changes instead of direct push
  .github/workflows/tag-and-build.yml
Labels: lgtm, approved
