Repository project-codeflare/codeflare-operator, pull requests merged in 2024-04, with the labels that each got.

#497 Add missing RBAC for oauth-proxy ClusterRoleBinding
  config/rbac/role.yaml
  pkg/controllers/raycluster_controller.go
Labels: lgtm, approved

#493 Refactor creation logic of ingress/routes into RayCluster Controller
  .github/workflows/e2e_tests.yaml
  main.go
  pkg/controllers/raycluster_controller.go
  pkg/controllers/support.go
Labels: lgtm, do-not-merge/hold

#492 Removed InstaScale & MCAD from release workflow
  .github/workflows/project-codeflare-release.yml
  .github/workflows/tag-and-build.yml
Labels: lgtm

#501 Clean removal of MCADv1 and Instascale
  Makefile
  config/crd/crd-appwrapper.yml
  config/crd/crd-quotasubtree.yml
  config/crd/crd-schedulingspec.yml
  config/crd/kustomization.yaml
  config/crd/mcad/kustomization.yaml
  config/e2e/config.yaml
  config/e2e/kustomization.yaml
  go.mod
  go.sum
  main.go
  pkg/config/config.go
  test/e2e/instascale_app_wrapper.go
  test/e2e/instascale_machinepool_test.go
  test/e2e/instascale_machineset_test.go
  test/e2e/instascale_nodepool_test.go
  test/e2e/mnist_pytorch_mcad_job_test.go
  test/e2e/mnist_rayjob_raycluster_test.go
  test/odh/mcad_ray_test.go
  test/odh/pytorch_mcad_test.go
  test/upgrade/olm_upgrade_test.go
Labels: lgtm, approved

#502 Update dependency versions for release v1.3.0
  README.md
  config/manager/params.env
Labels: lgtm, approved

#504 fix(manifests): remove emptry CRD and reference
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
Labels: lgtm

#506 Fix OLM upgrade test
  .github/workflows/olm_tests.yaml
Labels: lgtm, approved

#511 Update kuberay version to latest in make file
  Makefile
Labels: lgtm, approved

#515 Add a ConfigMap for e2e tests
  .github/workflows/e2e_tests.yaml
  config/e2e/config.yaml
  config/e2e/kustomization.yaml
Labels: lgtm, approved

#517 Adjust Kuberay dependency in the Makefile
  .github/workflows/tag-and-build.yml
Labels: lgtm, approved

#519 Update dependency versions for release v1.3.1
  Makefile
  README.md
  config/manager/params.env
Labels: lgtm, approved

#518 E2E tests: Deploy Kuberay before starting CodeFlare operator
  .github/workflows/e2e_tests.yaml
Labels: lgtm, approved

#520 Use Dnsmasq to provide DNS for KinD
  pkg/controllers/support.go
  test/e2e/mnist_rayjob_raycluster_test.go
Labels: lgtm, approved

#521 fix(manifests): missing namespace in CM stack-config
  config/manager/params.env
Labels: lgtm, approved

#527 Remove owner reference for ClusterRoleBinding to RayCluster
  pkg/controllers/raycluster_controller.go
Labels: lgtm, approved

#505 Adjust env tests for RayCluster controller
  .github/workflows/component_tests.yaml
  Makefile
  pkg/controllers/raycluster_controller_test.go
  pkg/controllers/suite_test.go
Labels: lgtm, approved

#531 Fix oauth-proxy cookie Secret
  pkg/controllers/raycluster_webhook.go
Labels: lgtm, approved

#534 Get go version for setup-go action from go.mod file
  .github/workflows/component_tests.yaml
  .github/workflows/e2e_tests.yaml
  .github/workflows/mnist-job-test-image.yml
  .github/workflows/olm_tests.yaml
  .github/workflows/operator-image.yml
  .github/workflows/precommit.yml
  .github/workflows/tag-and-build.yml
  .github/workflows/unit_tests.yml
  .github/workflows/verify_generated_files.yml
Labels: lgtm, approved

#535 Remove dangling MCAD and InstaScale references
  CONTRIBUTING.md
  README.md
  config/manifests/bases/codeflare-operator.clusterserviceversion.yaml
  main.go
Labels: lgtm, approved

#536 Update OWNERS
  OWNERS
Labels: lgtm, approved

#525 CVE fixes of High priority
  go.mod
  go.sum
Labels: lgtm, approved

#498 add additional function which creates network policy
  config/rbac/role.yaml
  go.mod
  go.sum
  main.go
  pkg/controllers/raycluster_controller.go
Labels: lgtm

#540 Update dependency versions for release v1.4.0
  Makefile
  README.md
  config/manager/params.env
  go.mod
  go.sum
Labels: lgtm, approved

#542 Fix OLM PR check by creating ConfigMap disabling oauth
  .github/workflows/olm_tests.yaml
Labels: lgtm, approved

#544 Altered network policy to allow all trafic for head & worker pods
  pkg/controllers/raycluster_controller.go
Labels: lgtm
